

- name: Ensures {{ install_dir }}/src dir exists
  file: path="{{ install_dir }}/src" state=directory

# Indigo

- name: Copy indigo archive on the server
  unarchive: src=indigo-1.1.tar.gz dest="{{ install_dir }}/src"

- name: Create a link from indigo-1.1 to indigo
  file: src="{{ install_dir }}/src/indigo-1.1" dest="{{ install_dir }}/indigo" state=link
  
- name: Copy settings
  template: src=settings.py dest="{{ install_dir }}/indigo"

# Indigo web
- name: Copy indigo web achive on the server
  unarchive: src=indigo-web-1.1.tar.gz dest="{{ install_dir }}/src"
 
- name: Collect static
  command: "{{ install_dir }}/web/bin/python {{ install_dir }}/web/project/manage.py collectstatic --noinput"


# Restart service
#- name: Restart the Indigo web service
#  service: name=indigo-web state=restarted
#  become: yes
#  become_method: sudo
