---
# This playbook deploys/installs a single node of the Indigo system

- name: Install a complete Indigo instance
  remote_user: indigo
  hosts: indigo

- include: databases.yml
- include: webservers.yml
- include: factstore.yml